version: "4"

services:
  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ogabrielnascr
      RABBITMQ_DEFAULT_PASS: ogabrielnascr
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ogabrielnascr
      POSTGRES_PASSWORD: ogabrielnascr
      POSTGRES_DB: lumienergy-bills
    volumes:
      - pgdata:/var/lib/postgresql/data
  lumienergy-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lumienergy-backend
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq-server
      - postgres
    env_file:
      - ./server/.env
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./server/src:/usr/src/app/src
volumes:
  pgdata:
