services:
  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ogabrielnascr
      RABBITMQ_DEFAULT_PASS: ogabrielnascr
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
  postgres:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ogabrielnascr
      POSTGRES_PASSWORD: ogabrielnascr
      POSTGRES_DB: lumienergy-bills
    volumes:
      - pgdata:/var/lib/postgresql/data
  lumienergy-backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: lumienergy-backend
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./server/.env
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - ./server:/usr/src/app/
  # lumienergy-front:
  #   build:
  #     context: "./frontend"
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./frontend:/app
volumes:
  pgdata:
